### ISSUE TITLE
The Single Sign on URL is not working

### ISSUE THREAD

**Issue by sara-arbabyazd** [thesamet/gerrit-saml-plugin#1]
Thanks for useful repo.
I followed your instruction to add gerrit to Okta. I am running Gerrit on AWS as a docker image from https://hub.docker.com/r/gerritforge/gerrit-ubuntu15.04/.

As mentioned in the Read me file I set the Single sign on URL to:
http://ec2-xxx.amazonaws.com/plugins/gerrit-saml-plugin/saml
and I checked the "Use this for Recipient URL and Destination URL"
The "Audience URI (SP Entity ID)" is also 
http://ec2-xxx.amazonaws.com/plugins/gerrit-saml-plugin/saml

However,  when I click on gerrit app in Okta, it redirects to 
http://ec2-xxx.amazonaws.com/plugins/gerrit-saml-plugin/ after authentication succeeds  
and if I manually remove the /plugins/gerrit-saml-plugin/ it goes to gerrit with Okta user information which is fine..
I tried setting http://ec2-xxx.amazonaws.com as the single sign on URL but it gives me "HTTP method POST is not supported by this URL" error... and the error-log file shows 
"Error in POST /plugins/gerrit-saml-plugin/saml
org.pac4j.saml.exceptions.SAMLException: org.pac4j.saml.exceptions.SAMLException: Intended destination"

**Comment by thesamet** [comment]
@sara-arbabyazd , can you double check that "default relay state" in Okta is left blank?

Also, the sign sign on URL must be $GERRIT_URL/plugins/gerrit-saml-plugin/saml like you initially tried.

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
