### ISSUE TITLE
Support for local non-interactive accounts

### ISSUE THREAD

**Issue by ottochiu** [thesamet/gerrit-saml-plugin#15]
Is there a way to setup local non-interactive accounts that can be used by automated systems such as Jenkins? I tried using `gerrit create-account` and providing a SSH key, but when I tried cloning the repo, I would get the publickey denied error.

**Comment by thesamet** [comment]
Sounds more like a permission issue that is unrelated to this plugin. Can you check if the problem persists when the plugin is disabled?

**Comment by ottochiu** [comment]
I did this by commenting out `filterClass = com.thesamet.gerrit.plugins.saml.SamlWebFilter` in `gerrit.config`. I was able to clone successfully, whereas before it would fail on publickey.

**Comment by ottochiu** [comment]
Another problem is that we have setup Gerrit Trigger on Jenkins with REST API enabled. It is unable to authenticate probably because it gets redirected to Okta.

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
