### ISSUE TITLE
project/assembly.sbt has non-existent library reference.

### ISSUE THREAD

**Issue by mikelupo** [thesamet/gerrit-saml-plugin#16]
I had to update the library reference in project/assembly.sbt from 0.14.0 to 0.14.9 to get the command: "sbt assembly" to succeed. 

else, I saw this warning:
::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

This resulted in an error downstream of the warning.
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.0: not found

**Comment by davido** [comment]
I was able to fix that, by manually downloading the required libraries. Basically, as documented [here](https://github.com/sbt/sbt-assembly/issues/245#issuecomment-350656200).

I also updated 0.14.0 to be 0.14.9:

```
  $ cat project/assembly.sbt

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
```

**Comment by mikelupo** [comment]
@davido 
I'm having trouble making sense of the reference in the thread you gave.

 I'm getting, module not found: org.scala-sbt#sbt;1.2.7
Here is entire gerrit-saml-plugin/project/assembly.sbt file.
```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
resolvers += Resolver.url("bintray-sbt-plugins", url("https://dl.bintray.com/eed3si9n/sbt-plugins/"))(Resolver.ivyStylePatterns)
libraryDependencies += "org.scala-sbt" % "sbt" % "1.2.7" % "provided"
```
Running sbt assembly inside the gerrit-saml-plugin project I just see this displayed:
``` Getting org.scala-sbt sbt 1.2.7  (this may take some time)...```
until it times out. Like 10 minutes later.

Curious if you could share your project/assembly.sbt file.

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
