### ISSUE TITLE
Clarify if auth=http_ldap is supported

### ISSUE THREAD

**Issue by kmbulebu** [thesamet/gerrit-saml-plugin#2]
Awesome work here. Can you clarify if http_ldap is supported? It's a common pattern to use SAML for authentication, but rely on LDAP for groups.

**Comment by thesamet** [comment]
I have not tried it (we don't use LDAP), but it looks like it should work. Can you try and report?

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
