### ISSUE TITLE
Consider to host the plugin on gerrit-review.googlesource.com

### ISSUE THREAD

**Issue by davido** [thesamet/gerrit-saml-plugin#21]
@thesamet Would you agree to host the plugin on gerrit-review.googlesource.com as canonical repository?

It would be easier to collaborate and review changes. Moreover, Gerrit Code Review outperforms GitHub, e.g. it's much easier to review changes or conduct a series of changes that depend on each other.

Note, that you could still maintain this repository as a mirror.

**Comment by jhansche** [comment]
IMO the plugin seems to have been abandoned by the author, so maybe it's best to just fork it straight to gerrit-review for now?  The plugin is broken in 2.16, so the fixes are necessary regardless :/

**Comment by thesamet** [comment]
Hey, thanks for all the PRs. Sorry for the delay, I'm travelling. I'm no longer actively maintaining this plugin, so feel free to fork and continue the development on GoogleSource. Happy to assist if that's needed.

**Comment by davido** [comment]
> I'm no longer actively maintaining this plugin, so feel free to fork and continue the development on GoogleSource.

Thanks!

@lucamilanesio I think we could then just import that current respoitory as a project to gerrit-review.googlesource.com and review/merge the PRs there? Can you look into importing the project? I will happily upload the PRs as changes to Gerrit.

**Comment by lucamilanesio** [comment]
> > I'm no longer actively maintaining this plugin, so feel free to fork and continue the development on GoogleSource.
> 
> Thanks!
> 
> @lucamilanesio I think we could then just import that current respoitory as a project to gerrit-review.googlesource.com and review/merge the PRs there? Can you look into importing the project? I will happily upload the PRs as changes to Gerrit.

Oh yes, I'll just create a post into the mailing list to propose the new project name and description and will create the repo afterwards.

**Comment by davido** [comment]
Thanks, @lucamilanesio!

**Comment by thesamet** [comment]
@lucamilanesio please let me know once this is set up, and I'll set up a notice on the root `README.md` to direct users to the new location.

**Comment by lucamilanesio** [comment]
> @lucamilanesio please let me know once this is set up, and I'll set up a notice on the root `README.md` to direct users to the new location.

Done, the plugin is now on https://gerrit-review.googlesource.com/admin/repos/plugins/saml
You are in the group of the maintainers, together with @davido and me. We are both committed to port the plugin to the most recent versions of Gerrit and keep on testing and integrating with more SAML providers.

**Comment by davido** [comment]
> Done, the plugin is now on https://gerrit-review.googlesource.com/admin/repos/plugins/saml

Thanks, @lucamilanesio!

As you pointed out on the mailing list: [1], some commits cannot be imported, because of the missing CLA from the users. Particularly, these PRs from @revaultch:

https://github.com/thesamet/gerrit-saml-plugin/pull/3
https://github.com/thesamet/gerrit-saml-plugin/pull/4
https://github.com/thesamet/gerrit-saml-plugin/pull/5

and these PRs from @mikelupo:

https://github.com/thesamet/gerrit-saml-plugin/pull/12
https://github.com/thesamet/gerrit-saml-plugin/pull/13

were not imported.

@revaultch, @mikelupo: Could you please sign in on gerrit-review.googlesource.com and accept the ACL? Then we could import the missing commits as well.

Thank you in advance for helping out with the import of the repository to gerrit-review.googlesource.com!

[1] https://groups.google.com/d/topic/repo-discuss/aPfJX6T0n0k/discussion

**Comment by mikelupo** [comment]
Trying to accept the ACL from my mobile. Can you see that I completed?

**Comment by davido** [comment]
> Can you see that I completed?

mlupo at akamai dot com is still unknown on gerrit-review.googlesource.com

**Comment by mikelupo** [comment]
@davido, I was able to complete the Google CLA. Is that all you needed from me?

Thanks!
Mike

**Comment by mikelupo** [comment]
Oops Mails crossed..
I don’t submit code under that user. If I did that’s an error. I only submit code under my mikelupo at gmail. Our SSO at work works with google so I might have inadvertently.
Without our legal team’s sign off, I cannot accept a license agreement under my work address.

**Comment by davido** [comment]
@mikelupo Indeed mikelupo at gmail dot com is known on gerrit-review.googlesource.com. Let me re-write your 2 commits then from Akamai to GMail domain.

Done here:

* https://gerrit-review.googlesource.com/c/plugins/saml/+/209218
* https://gerrit-review.googlesource.com/c/plugins/saml/+/209219

**Comment by davido** [comment]
@arraen: Can you please also register on googlesource.com and accept the ACL? We need it to import this PR: [1] here: [2].

Thanks!

* [1] https://github.com/thesamet/gerrit-saml-plugin/pull/13
 * [2] https://gerrit-review.googlesource.com/c/plugins/saml/+/209220

**Comment by thesamet** [comment]
Bulk closing all open issues in this repo and archiving this project. Thank you all for taking this plugin forward at https://gerrit.googlesource.com/plugins/saml/
