### ISSUE TITLE
 plugin issues with version gerrit 2.16 and 3.00

### ISSUE THREAD

**Issue by snarmaev** [thesamet/gerrit-saml-plugin#24]
After an upgrade to 2.16 from 2.15, I am encountering a multiple errors related to login. Seems like the latest stable version for gerrit-saml-plugin is 2.15. Will you have any future updates to the version 2.16 or 3.0?

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
