### ISSUE TITLE
Why is the Java Keystore Required

### ISSUE THREAD

**Issue by jammerful** [thesamet/gerrit-saml-plugin#7]
Hello,

I don't understand why functionally the Java Keystore (JKS) is required? The plugin seems to assume that the X509 Certificate is located in the metadata and not in the JKS. So what is the private key in the JKS provide?

Thanks

**Comment by thesamet** [comment]
It's a requirement of the underlying pac4j library see [1] and [2]. Would be happy to merge a PR that replaces pac4j with another (sufficiently reputable) library that doesn't have this requirement.

[1] https://github.com/pac4j/pac4j/wiki/Clients
[2] https://groups.google.com/forum/#!topic/pac4j-users/MwF_M5eFh2E)

**Comment by jammerful** [comment]
Great, I'll take a look.
