### ISSUE TITLE
Support for memberOf attribute?

### ISSUE THREAD

**Issue by jammerful** [thesamet/gerrit-saml-plugin#8]
Hello,

My IdP is backed by Active Directory and I would like Gerrit to be able to store an attribute called memberOf sent by my IdP in the SAML token, how would you feel about merging a PR that enables this?

Thanks

**Comment by thesamet** [comment]
Sure.

**Comment by steven-aerts** [comment]
I have a possible implementation for it in review here: https://gerrit-review.googlesource.com/c/plugins/saml/+/217820

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
