### ISSUE TITLE
Unable to use this plugin with jetbrains HUB

### ISSUE THREAD

**Issue by surabujin** [thesamet/gerrit-saml-plugin#9]
Hi.

I have installed this plugin according to README in this repo. But all my attempts to authenticate are failed with "SAMLException: Signature is not trusted". I can't understand wich signature is not trusted. Which cert should I add to trusted and where... I have tried to add all affected certificates - cert used to wrap http in https on HUB. Cert I have created for SAML protocol in HUB, cert I have created for this plugin.

I have tried to add them in created keystore, in global java cacerts, in OS global cacerts...

Chunk of log with full traceback in attachment.

[saml-gerrit-error.txt](https://github.com/thesamet/gerrit-saml-plugin/files/501793/saml-gerrit-error.txt)

Workflow:
- open root gerrit url https://ruling.nyaka.org/review
- redirect to HUB
- enter login/pass
- redirect to https://ruling.nyaka.org/review/plugins/gerrit-saml-plugin/saml and see message "server error"

**Comment by thesamet** [comment]
I see "No valid subject assertion found in response" which makes me think that the pac4j (the SAML library we're using) can't parse the SAML payload passed. The subject is usually the username/email of the user - perhaps it can be configured through "Default Name Id": https://www.jetbrains.com/help/hub/2.5/Hub-Parameters-as-IdP.html

**Comment by surabujin** [comment]
The option "Default name id" can be set to one of the variants: 
<img width="614" alt="screen shot 2016-09-30 at 1 46 22 am" src="https://cloud.githubusercontent.com/assets/2862761/18975003/c4e97bee-86af-11e6-82eb-0983c1f3e0eb.png">

I have tried all of them, just now... errors the same, with all variants.

I have a response, sent from hub to gerrit. I will send it to you on email.

**Comment by surabujin** [comment]
I have fond the issue - the problem was in missing certificate in SAML metadata. I have added certificate there and it passed... at least it passed authentication. It cost me several hours of reading sources for this plugin, for pac4j and opensaml.

After that I have faced with new problem - it tries to create new user with information received from SAML... and it use user email as login. As result - it failed with:

```
[2016-10-01 17:30:58,407] [HTTP-32] INFO  org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver : Using SP entity ID https://ruling.nyaka.org/review/plugins/gerrit-saml-plug
in/saml
[2016-10-01 17:30:59,271] [HTTP-32] ERROR com.google.gerrit.server.account.AccountManager : Cannot assign user name "test@test.com" to account 1000007; name does not conform.
[2016-10-01 17:30:59,287] [HTTP-32] ERROR com.google.gerrit.httpd.auth.container.HttpLoginServlet : Unable to authenticate user "test@test.com"
com.google.gerrit.server.account.AccountUserNameException: Cannot assign user name "test@test.com" to account 1000007; name does not conform.
        at com.google.gerrit.server.account.AccountManager.handleSettingUserNameFailure(AccountManager.java:327)
        at com.google.gerrit.server.account.AccountManager.create(AccountManager.java:276)
        at com.google.gerrit.server.account.AccountManager.authenticate(AccountManager.java:114)
        at com.google.gerrit.httpd.auth.container.HttpLoginServlet.doGet(HttpLoginServlet.java:119)
```

Manipulations with option "Default Name Id" give no effect. I always see in responses from HUB user's email in NameID field, despite value of "Default Name Id".

**Comment by thesamet** [comment]
This should be solvable. In gerrit configuration, set `saml.userNameAttr` to whatever SAML attribute you'd like the plugin to use as the user name.

**Comment by surabujin** [comment]
It should be nice... but - there is no any other attributes, except email in auth response. At least I don't see any in response in hub log. (attached)

May be it send more, then I see in logs... but how I will know the attribute name in this case?..

[saml-response.txt](https://github.com/thesamet/gerrit-saml-plugin/files/504641/saml-response.txt)

**Comment by thesamet** [comment]
That might be a limitation in Jetbrains Hub. Gerrit (or this plugin) have no way to guess what username should be assigned to this user. Most identity providers have different ways to add custom attributesto the SAML response. For example, Okta can pass the user prefix of an email address (what's left of the @ sign) as the username, so if your Gerrit is open to just one domain this would make sense.

**Comment by surabujin** [comment]
I understand that this is limitation of HUB... I thought better about this product. I have made a ticket about this issue in their bug tracker. (https://youtrack.jetbrains.com/issue/JPS-4436)

I can't use local part or email address as user name... even if I can configure HUB/gerrit for this. For now I will install OpenLDAP and use it as central identity provider. 

I will think about moving back to HUB SAML2, If jetbrains manage to make it usable.

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
